code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EQuimper.react-native-react-redux
code --install-extension PeterJausovec.vscode-docker
code --install-extension deerawan.vscode-faker
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.jupyter
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension himanoa.Python-autopep8
code --install-extension hollowtree.vue-snippets
code --install-extension johnpapa.Angular2
code --install-extension liuji-jim.vue
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension neilbrayfield.php-docblocker
code --install-extension njpwerner.autodocstring
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension robertohuertasm.vscode-icons
code --install-extension techer.open-in-browser
code --install-extension vscjava.vscode-java-debug
code --install-extension vsmobile.vscode-react-native
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhoulv.opencodeview
